name: glitch_camera_app
description: A glitch camera app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  image: ^4.1.7
  vector_math: ^2.1.4
  path_provider: ^2.1.4
  gal: ^2.3.0
  flutter_quick_video_encoder: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  shaders:
    - shaders/glitch.frag
